---
# https://grr-doc.readthedocs.io/en/stable/installing-grr-server/from-release-deb.html
- name: Configure and Install GRR Server
  hosts: grr_servers
  become: yes
  vars_files:
    - vars/grr_config_vars.yml

  tasks:

    - name: Install required packages
      ansible.builtin.apt:
        name:
          - wget
          - vim
          - mysql-server
          - python3-dev
          - python3-pip
        state: present
        update_cache: yes
      register: install_deps
      when: ansible_os_family == "Debian"

    - name: Install PyMySQL python dependency
      ansible.builtin.pip:
        name: PyMySQL
        state: present
      when: install_deps.changed and ansible_os_family == "Debian"

    - name: Configure MySQL for GRR (max_allowed_packet and function creators)
      ansible.builtin.lineinfile:
        path: /etc/mysql/mysql.conf.d/mysqld.cnf
        regexp: '^\[mysqld\]$'
        line: |
          [mysqld]
          max_allowed_packet={{ mysql_max_allowed_packet }}
          log_bin_trust_function_creators={{ mysql_log_bin_trust_function_creators }}
        insertafter: EOF
        state: present
        backup: yes
      notify: Restart MySQL
      when: ansible_os_family == "Debian"

    - name: Force all notified handlers to run immediately (for MySQL config)
      ansible.builtin.meta: flush_handlers
      when: ansible_os_family == "Debian"

    - name: Create GRR and Fleetspeak databases and users using shell
      ansible.builtin.shell: |
        mysql -u root <<EOF
        CREATE DATABASE IF NOT EXISTS {{ grr_database_name }};
        CREATE USER IF NOT EXISTS '{{ grr_database_user }}'@'localhost' IDENTIFIED BY '{{ grr_database_password }}';
        GRANT ALL PRIVILEGES ON {{ grr_database_name }}.* TO '{{ grr_database_user }}'@'localhost';

        CREATE DATABASE IF NOT EXISTS {{ fleetspeak_database_name }};
        CREATE USER IF NOT EXISTS '{{ fleetspeak_database_user }}'@'localhost' IDENTIFIED BY '{{ fleetspeak_database_password }}';
        GRANT ALL PRIVILEGES ON {{ fleetspeak_database_name }}.* TO '{{ fleetspeak_database_user }}'@'localhost';

        FLUSH PRIVILEGES;
        EOF
      args:
        creates: /var/lib/mysql/{{ grr_database_name }}
      when: ansible_os_family == "Debian"

    - name: Download the GRR server DEB package
      ansible.builtin.get_url:
        url: "{{ grr_deb_url }}"
        dest: "/tmp/grr-server_{{ grr_version }}_amd64.deb"
        mode: '0644'
      when: ansible_os_family == "Debian"

    - name: Install the GRR server DEB package
      ansible.builtin.apt:
        deb: "/tmp/grr-server_{{ grr_version }}_amd64.deb"
        state: present
      environment:
        DEBIAN_FRONTEND: noninteractive
      notify: Restart GRR Services
      when: ansible_os_family == "Debian"

    - name: Check if GRR configuration file exists for idempotency
      ansible.builtin.stat:
        path: /etc/grr/server.local.yaml
      register: grr_config_stat
      when: ansible_os_family == "Debian"

    - name: Generate random CSRF key if configuration file is new
      ansible.builtin.set_fact:
        grr_csrf_secret_key: "{{ lookup('ansible.builtin.password', '/dev/null length=64 chars=ascii_letters,digits,punctuation') }}"
      when: not grr_config_stat.stat.exists and ansible_os_family == "Debian"

    - name: Copy custom server configuration file to /etc/grr/server.local.yaml
      ansible.builtin.template:
        src: grr_server_config.j2
        dest: /etc/grr/server.local.yaml
        owner: root
        group: root
        mode: '0644'
      when: not grr_config_stat.stat.exists and ansible_os_family == "Debian"

    - name: Set permissions for /GRRlog.txt
      ansible.builtin.file:
        path: /GRRlog.txt
        mode: '0766'
        state: file
      ignore_errors: yes
      when: ansible_os_family == "Debian"

    - name: Run grr_config_updater generate_keys
      ansible.builtin.command: grr_config_updater generate_keys
      args:
        creates: /etc/grr/server.pem
      when: not grr_config_stat.stat.exists and ansible_os_family == "Debian"

    - name: Create initial GRR admin user
      ansible.builtin.command: >
        grr_config_updater add_user 
        {{ grr_admin_username }} 
        --password {{ grr_admin_password }} 
        --admin true
      args:
        creates: /etc/grr/users/{{ grr_admin_username }}.yaml
      notify: Restart GRR Services
      when: not grr_config_stat.stat.exists and ansible_os_family == "Debian"

    - name: Check if fleetspeak configuration file exists
      ansible.builtin.stat:
        path: /etc/fleetspeak-server/fleetspeak_config.config
      register: fleetspeak_config_stat
      when: ansible_os_family == "Debian"

    - name: Write Fleetspeak Configurator Input File
      ansible.builtin.template:
        src: fleetspeak_config.j2
        dest: /etc/fleetspeak-server/fleetspeak_config.config
        owner: root
        group: root
        mode: '0644'
      when: not fleetspeak_config_stat.stat.exists and ansible_os_family == "Debian"

    - name: Check if fleetspeak server.components.config file exists
      ansible.builtin.stat:
        path: /etc/fleetspeak-server/server.components.config
      register: fleetspeak_components_stat
      when: ansible_os_family == "Debian"

    - name: Run fleetspeak-config (Generates Certs and Component Configs)
      ansible.builtin.command: fleetspeak-config -config /etc/fleetspeak-server/fleetspeak_config.config
      args:
        creates: /etc/fleetspeak-server/server.components.config
      when: not fleetspeak_components_stat.stat.exists and ansible_os_family == "Debian"

    - name: Generate client installer binaries (Repacking)
      ansible.builtin.command: grr_config_updater repack_clients
      when: ansible_os_family == "Debian"

    - name: Display GRR Admin UI URL
      ansible.builtin.debug:
        msg: "GRR Server setup complete! Access the Admin UI at: http://{{ grr_server_hostname }}:{{ grr_adminui_port }} (User: {{ grr_admin_username }}, Pass: {{ grr_admin_password }})"
      when: ansible_os_family == "Debian"

  handlers:
    - name: Restart MySQL
      ansible.builtin.service:
        name: mysql
        state: restarted

    - name: Restart GRR Services
      ansible.builtin.service:
        name: grr-server
        state: restarted